"""Fix fashion models relationships

Revision ID: 85a803d60572
Revises: 2f2369c3a02d
Create Date: 2025-07-26 18:45:13.591064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a803d60572'
down_revision: Union[str, None] = '2f2369c3a02d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('product_variants', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('purchase_order_items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('purchase_orders', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('styles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('styles', 'created_at')
    op.drop_column('purchase_orders', 'created_at')
    op.drop_column('purchase_order_items', 'created_at')
    op.drop_column('product_variants', 'created_at')
    op.drop_column('collections', 'created_at')
    # ### end Alembic commands ###
